/**
 * Story 04 T2 — CLI adapter for `export initiative`.
 * Calls the use case, then writes the cosmetic tree + INDEX.md + manifest.
 * All filesystem I/O lives here (B5/B8 — the use case never touches the FS).
 */
import { writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import type { GraphPackage } from "../../app/graph/graph-package.ts";
import { writePackage } from "./graph-md/serialize.ts";

type ExportUC = { execute(initiativeId: string): Promise<GraphPackage> };

type HandlerResult = {
  exitCode: number;
  stdout: string[];
  stderr: string[];
};

/**
 * Handle `export initiative --id <id> --out <dir>`.
 * Returns a result object — never throws, never calls `process.exit`.
 */
export async function runExportInitiative(
  args: { id: string; out: string | undefined },
  uc: ExportUC,
): Promise<HandlerResult> {
  if (!args.out) {
    return {
      exitCode: 1,
      stdout: [],
      stderr: ["error: --out <dir> is required"],
    };
  }

  const pkg = await uc.execute(args.id);

  // Initiative directory is named by a kebab-case slug of the initiative name.
  const nameSlug = pkg.initiative.name.toLowerCase().replace(/\s+/g, "-");
  const rootDir = join(args.out, nameSlug);

  // Ensure the root dir exists before writing INDEX + manifest.
  await mkdir(rootDir, { recursive: true });

  // Write node markdown files (atomic rename per S3 — implemented in writePackage).
  await writePackage(rootDir, pkg);

  // Write INDEX.md — human-readable read-only view (content is unconstrained).
  const taskLines = pkg.tasks.map((t) => `- ${t.title}`);
  const indexContent = [
    `# ${pkg.initiative.name}`,
    "",
    "Generated by kanthord. Do not import this file.",
    "",
    "## Tasks",
    "",
    ...taskLines,
    "",
  ].join("\n");
  await writeFile(join(rootDir, "INDEX.md"), indexContent, "utf8");

  // Write .kanthord-export.json manifest.
  if (pkg.manifest !== undefined) {
    await writeFile(
      join(rootDir, ".kanthord-export.json"),
      JSON.stringify(pkg.manifest, null, 2),
      "utf8",
    );
  }

  return {
    exitCode: 0,
    stdout: [`exported to ${rootDir}`],
    stderr: [],
  };
}
